import {
  BarChart3,
  Calculator,
  Code,
  FileText,
  Globe,
  ImageIcon,
  Palette,
  Plus,
  Settings,
  Shuffle,
  Type,
} from "lucide-react";

export const categoriesAndTools: any = {
  // all
  "domain-tools": {
    name: "Domain Tools",
    description:
      "Comprehensive domain analysis and management tools for webmasters and SEO professionals",
    color: "from-blue-500 to-cyan-500",
    tools: [
      {
        name: "Domain Authority Checker",
        description: "Check domain authority and page authority scores",
        icon: "🔍",
        slug: "domain-authority-checker",
        level: "pro", // Added level
      },
      {
        name: "Domain IP History",
        description: "View historical IP addresses for any domain",
        icon: "📊",
        slug: "domain-ip-history",
        level: "free", // Added level
      },
      {
        name: "Domain Age Checker",
        description: "Find out when a domain was first registered",
        icon: "📅",
        slug: "domain-age-checker",
        level: "free", // Added level
      },
      {
        name: "Reverse IP Domains",
        description: "Find all domains hosted on the same IP address",
        icon: "🔄",
        slug: "reverse-ip-domains",
        level: "pro", // Added level
      },
      {
        name: "Google Malware Checker",
        description: "Check if a website is flagged by Google for malware",
        icon: "🛡️",
        slug: "google-malware-checker",
      },
      {
        name: "Backlink Maker",
        description: "Generate high-quality backlinks for your website",
        icon: "🔗",
        slug: "backlink-maker",
      },
      {
        name: "Broken Links Checker",
        description: "Find and fix broken links on your website",
        icon: "🔧",
        slug: "broken-links-checker",
      },
      {
        name: "Google Indexer",
        description: "Check if your pages are indexed by Google",
        icon: "🔍",
        slug: "google-indexer",
      },
      {
        name: "Reverse Whois Checker",
        description:
          "Find domains registered by the same person or organization",
        icon: "👤",
        slug: "reverse-whois-checker",
        level: "pro", // Added level
      },
      {
        name: "Alexa Rank Checker",
        description: "Check website's Alexa traffic ranking",
        icon: "📈",
        slug: "alexa-rank-checker",
      },
      {
        name: "Blog Search Tool",
        description: "Search and analyze blog content across domains",
        icon: "📝",
        slug: "blog-search-tool",
      },
      {
        name: "Link Extractor",
        description: "Extract all links from any webpage",
        icon: "🔗",
        slug: "link-extractor",
      },
      {
        name: "Social Media Counter",
        description: "Count social media shares for any URL",
        icon: "📱",
        slug: "social-media-counter",
      },
      {
        name: "Google PR Checker",
        description: "Check Google PageRank for websites",
        icon: "📊",
        slug: "google-pr-checker",
      },
      {
        name: "Domain Whois Checker",
        description: "Get detailed whois information for any domain",
        icon: "ℹ️",
        slug: "domain-whois-checker",
        level: "free", // Added level
      },
    ],
  },
  //all
  "website-management": {
    name: "Website Management Tools",
    description:
      "Essential tools for website analysis, monitoring, and optimization",
    color: "from-violet-500 to-purple-500",
    tools: [
      // {
      //   name: "Link Analyzer",
      //   description: "Analyze links on your website for SEO and performance",
      //   icon: "🔗",
      //   slug: "link-analyzer",
      //   level: "pro", // Badge label: pro
      // },
      {
        name: "Google Malware Checker",
        description:
          "Scan your website for malware and security threats using Google's safe browsing technology.",
        icon: "🦠",
        slug: "google-malware-checker",
        level: "free", // Badge label: pro
      },
      {
        name: "Website Links Count Checker",
        description: "Count the number of links on a webpage",
        icon: "🔗",
        slug: "links-count-checker",
        level: "free", // Badge label: free
      },
      // {
      //   name: "Broken Links Finder",
      //   description: "Identify broken links on your website",
      //   icon: "🔗",
      //   slug: "broken-links-finder",
      //   level: "pro", // Badge label: pro
      // },
      // {
      //   name: "Links Extractor",
      //   description: "Extract all links from any webpage",
      //   icon: "🔗",
      //   slug: "links-extractor",
      //   level: "pro", // Badge label: free
      // },
      // {
      //   name: "Reverse NS Checker",
      //   description: "Check reverse name server records",
      //   icon: "🔄",
      //   slug: "reverse-ns-checker",
      //   level: "pro", // Badge label: pro
      // },
      {
        name: "Detect CMS",
        description: "Detect what CMS a website is using",
        icon: "🔍",
        slug: "detect-cms",
        level: "free", // Badge label: free
      },
    ],
  },
  // all
  "more-tools": {
    name: "More Tools",
    description:
      "Additional specialized tools and utilities for various purposes",
    color: "from-rose-500 to-pink-500",
    tools: [
      {
        name: "Blog Search Tool",
        description: "Search and discover blogs on various topics",
        icon: "🔍",
        slug: "blog-search-tool",
        level: "free", // Badge label: free
      },
      {
        name: "Article Rewriter",
        description: "Rewrite articles to create unique content",
        icon: "✍️",
        slug: "article-rewriter",
        level: "pro", // Badge label: pro
      },
      {
        name: "Plagiarism Checker",
        description: "Check content for plagiarism and originality",
        icon: "🔎",
        slug: "plagiarism-checker",
        level: "pro", // Badge label: pro
      },
    ],
  },
  // all
  "developer-tools": {
    name: "Developer Tools",
    description:
      "Essential tools for web developers and programmers to optimize and debug code",
    color: "from-green-500 to-emerald-500",
    tools: [
      {
        name: "DNS Records Checker",
        description: "Check DNS records for any domain",
        icon: "🌐",
        slug: "dns-records",
        level: "free",
      },
      {
        name: "HTML Encoder/Decoder",
        description: "Encode and decode HTML entities",
        icon: "📝",
        slug: "html-encoder-decoder",
        level: "free",
      },
      {
        name: "Minify HTML",
        description: "Compress HTML code by removing unnecessary characters",
        icon: "🗜️",
        slug: "minify-html",
        level: "free",
      },
      {
        name: "JS Beautifier",
        description: "Format and beautify JavaScript code",
        icon: "✨",
        slug: "js-beautifier",
        level: "free",
      },
      {
        name: "PHP Beautifier",
        description: "Format and beautify PHP code",
        icon: "🐘",
        slug: "php-beautifier",
        level: "free",
      },
      {
        name: "CSS Beautifier",
        description: "Format and beautify CSS code",
        icon: "🎨",
        slug: "css-beautifier",
        level: "free",
      },
      {
        name: "JSON Beautifier",
        description: "Format and validate JSON data",
        icon: "📋",
        slug: "json-beautifier",
        level: "free",
      },
      {
        name: "XML Beautifier",
        description: "Format and validate XML data",
        icon: "📄",
        slug: "xml-beautifier",
        level: "free",
      },
      {
        name: "URL Encoder/Decoder",
        description: "Encode and decode URLs",
        icon: "🔗",
        slug: "url-encoder-decoder",
        level: "free",
      },
      {
        name: "Server Status Checker",
        description: "Check if a server is online and responsive",
        icon: "🖥️",
        slug: "server-status",
        level: "free",
      },
      // {
      //   name: "Online Ping Website Tool",
      //   description: "Ping websites to check their availability",
      //   icon: "📶",
      //   slug: "ping-website",
      //   level: "free",
      // },
      // {
      //   name: "Webpage Screen Resolution Simulator",
      //   description: "Simulate different screen resolutions for webpages",
      //   icon: "🖥️",
      //   slug: "screen-resolution-simulator",
      //   level: "pro",
      // },
      // {
      //   name: "Page Size Checker",
      //   description: "Check the size of a webpage",
      //   icon: "📏",
      //   slug: "page-size-checker",
      //   level: "free",
      // },
      {
        name: "Get Source Code of Webpage",
        description: "Retrieve the source code of any webpage",
        icon: "📜",
        slug: "source-code-retriever",
        level: "pro",
      },
      // {
      //   name: "Class C IP Checker",
      //   description: "Check Class C IP addresses",
      //   icon: "🔍",
      //   slug: "class-c-ip-checker",
      //   level: "pro",
      // },
      // {
      //   name: "Page Speed Checker",
      //   description: "Analyze the speed of a webpage",
      //   icon: "🚀",
      //   slug: "page-speed-checker",
      //   level: "pro",
      // },
      // {
      //   name: "Google Cache Checker",
      //   description: "Check if a page is cached by Google",
      //   icon: "🗂️",
      //   slug: "google-cache-checker",
      //   level: "free",
      // },
      // {
      //   name: "Page Comparison",
      //   description: "Compare two webpages for differences",
      //   icon: "🔍",
      //   slug: "page-comparison",
      //   level: "pro",
      // },
      // {
      //   name: "Similar Page Checker",
      //   description: "Find similar pages to a given URL",
      //   icon: "🔗",
      //   slug: "similar-page-checker",
      //   level: "pro",
      // },
      // {
      //   name: "What is My IP",
      //   description: "Find out your public IP address",
      //   icon: "🌐",
      //   slug: "what-is-my-ip",
      //   level: "free",
      // },
      // {
      //   name: "DNS Propagation Checker",
      //   description: "Check DNS propagation status",
      //   icon: "🌍",
      //   slug: "dns-propagation-checker",
      //   level: "pro",
      // },
      // {
      //   name: "Server Port Scanner",
      //   description: "Scan server ports for open services",
      //   icon: "🔌",
      //   slug: "server-port-scanner",
      //   level: "pro",
      // },
      // {
      //   name: "IP Location",
      //   description: "Find the geographical location of an IP address",
      //   icon: "📍",
      //   slug: "ip-location",
      //   level: "pro",
      // },
      // {
      //   name: "Different Location Pings",
      //   description: "Ping a server from different locations",
      //   icon: "🌎",
      //   slug: "location-pings",
      //   level: "pro",
      // },
      // {
      //   name: "Traceroute Tool",
      //   description: "Trace the route packets take to a network host",
      //   icon: "🛤️",
      //   slug: "traceroute-tool",
      //   level: "pro",
      // },
      // {
      //   name: "Website Page Snooper",
      //   description: "Snoop on webpage details and metadata",
      //   icon: "🔍",
      //   slug: "page-snooper",
      //   level: "pro",
      // },
      // {
      //   name: "Domain IP Lookup",
      //   description: "Find the IP address of a domain",
      //   icon: "🔍",
      //   slug: "domain-ip-lookup",
      //   level: "pro",
      // },
      {
        name: "Minify CSS",
        description: "Compress CSS code by removing unnecessary characters",
        icon: "🗜️",
        slug: "minify-css",
        level: "free",
      },
      {
        name: "Minify JS",
        description:
          "Compress JavaScript code by removing unnecessary characters",
        icon: "🗜️",
        slug: "minify-js",
        level: "free",
      },
      {
        name: "Minify JSON",
        description: "Compress JSON data by removing unnecessary characters",
        icon: "🗜️",
        slug: "minify-json",
        level: "free",
      },
    ],
  },
  // all
  "text-tools": {
    name: "Text Tools",
    description:
      "Powerful text manipulation and formatting tools for content creators",
    color: "from-purple-500 to-pink-500",
    tools: [
      // {
      //   name: "Keyword Position Checker",
      //   description: "Check the position of keywords in search results",
      //   icon: "🔍",
      //   slug: "keyword-position-checker",
      //   level: "pro",
      // },
      {
        name: "Word Counter",
        description: "Count the number of words in a text",
        icon: "🔢",
        slug: "word-counter",
        level: "free",
      },
      // {
      //   name: "Keyword Density Checker",
      //   description: "Analyze the density of keywords in a text",
      //   icon: "📊",
      //   slug: "keyword-density-checker",
      //   level: "pro",
      // },
      // {
      //   name: "URL Rewriting Tool",
      //   description: "Rewrite URLs for SEO optimization",
      //   icon: "🔗",
      //   slug: "url-rewriting-tool",
      //   level: "pro",
      // },
      {
        name: "Code to Text Ratio Checker",
        description: "Calculate the code to text ratio in a document",
        icon: "📊",
        slug: "code-to-text-ratio",
        level: "free",
      },
      // {
      //   name: "Email Privacy",
      //   description: "Check and improve the privacy of your email content",
      //   icon: "🔒",
      //   slug: "email-privacy",
      //   level: "pro",
      // },
      // {
      //   name: "Keyword Suggestion Tool",
      //   description: "Generate keyword suggestions for SEO",
      //   icon: "💡",
      //   slug: "keyword-suggestion-tool",
      //   level: "pro",
      // },
      // {
      //   name: "AI Email Writer",
      //   description: "Generate professional emails using AI",
      //   icon: "✉️",
      //   slug: "ai-email-writer",
      //   level: "pro",
      // },
      // {
      //   name: "Sentence Expander",
      //   description: "Expand sentences to add more detail",
      //   icon: "🔍",
      //   slug: "sentence-expander",
      //   level: "pro",
      // },
      {
        name: "Invisible Character",
        description: "Insert invisible characters into text",
        icon: "👻",
        slug: "invisible-character",
        level: "free",
      },
      // {
      //   name: "Paragraph Expander",
      //   description: "Expand paragraphs to add more content",
      //   icon: "📜",
      //   slug: "paragraph-expander",
      //   level: "pro",
      // },
      // {
      //   name: "Humanize AI Text",
      //   description: "Make AI-generated text sound more human",
      //   icon: "🤖",
      //   slug: "humanize-ai-text",
      //   level: "pro",
      // },
      // {
      //   name: "AI Sentence Shortener",
      //   description: "Shorten sentences using AI",
      //   icon: "✂️",
      //   slug: "ai-sentence-shortener",
      //   level: "pro",
      // },
      {
        name: "Text to Word",
        description: "Convert text documents to Word format",
        icon: "📄",
        slug: "text-to-word",
        level: "free",
      },
      {
        name: "Text to PDF",
        description: "Convert text documents to PDF format",
        icon: "📄",
        slug: "text-to-pdf",
        level: "free",
      },
      {
        name: "Text Repeater",
        description: "Repeat text multiple times",
        icon: "🔁",
        slug: "text-repeater",
        level: "free",
      },
      // {
      //   name: "Grammar Checker",
      //   description: "Check and correct grammar in your text",
      //   icon: "✅",
      //   slug: "grammar-checker",
      //   level: "free",
      // },
      // {
      //   name: "Spell Checker",
      //   description: "Check and correct spelling in your text",
      //   icon: "📝",
      //   slug: "spell-checker",
      //   level: "free",
      // },
      // {
      //   name: "Keyword / Total Words",
      //   description: "Calculate the ratio of keywords to total words",
      //   icon: "📈",
      //   slug: "keyword-total-words",
      //   level: "pro",
      // },
      // {
      //   name: "Text Compare",
      //   description: "Compare two text documents for differences",
      //   icon: "🔍",
      //   slug: "text-compare",
      //   level: "pro",
      // },
      {
        name: "Word Combiner",
        description: "Combine words to create new terms",
        icon: "🔗",
        slug: "word-combiner",
        level: "free",
      },
      {
        name: "ASCII to Text",
        description: "Convert ASCII codes to text",
        icon: "🔤",
        slug: "ascii-to-text",
        level: "free",
      },
      {
        name: "Text to ASCII",
        description: "Convert text to ASCII codes",
        icon: "🔤",
        slug: "text-to-ascii",
        level: "free",
      },
      // {
      //   name: "Online Text Editor",
      //   description: "Edit and format your text online",
      //   icon: "📝",
      //   slug: "online-text-editor",
      //   level: "free",
      // },
      {
        name: "Words to Pages",
        description: "Calculate the number of pages from word count",
        icon: "📄",
        slug: "word-pages",
        level: "free",
      },
    ],
  },
  // all ==> 1
  calculators: {
    name: "Calculators",
    description:
      "Mathematical and financial calculators for everyday calculations",
    color: "from-orange-500 to-red-500",
    tools: [
      {
        name: "Link Price Calculator",
        description: "Calculate the price of links based on various metrics",
        icon: "🔗", // Replace with a professional icon
        slug: "link-price-calculator",
        level: "pro",
      },
      {
        name: "AdSense Calculator",
        description: "Calculate potential AdSense earnings",
        icon: "💵", // Replace with a professional icon
        slug: "adsense-calculator",
        level: "pro",
        component: "Hello",
      },
      {
        name: "PayPal Fee Calculator",
        description: "Calculate PayPal transaction fees",
        icon: "💳", // Replace with a professional icon
        slug: "paypal-fee-calculator",
        level: "free",
      },
      {
        name: "LTV Calculator",
        description: "Calculate customer lifetime value",
        icon: "📈", // Replace with a professional icon
        slug: "ltv-calculator",
        level: "pro",
      },
      {
        name: "CPC Calculator",
        description: "Calculate cost per click for advertising",
        icon: "📊", // Replace with a professional icon
        slug: "cpc-calculator",
        level: "pro",
      },
      {
        name: "CPM Calculator",
        description: "Calculate cost per mille for advertising",
        icon: "📊", // Replace with a professional icon
        slug: "cpm-calculator",
        level: "pro",
      },
      {
        name: "Discount Calculator",
        description: "Calculate discounts and final prices",
        icon: "💰", // Replace with a professional icon
        slug: "discount-calculator",
        level: "free",
      },
      {
        name: "Binary Calculator",
        description: "Perform calculations in binary number system",
        icon: "🔢", // Replace with a professional icon
        slug: "binary-calculator",
        level: "free",
      },
      {
        name: "HEX Calculator",
        description: "Perform calculations in hexadecimal number system",
        icon: "🔢", // Replace with a professional icon
        slug: "hex-calculator",
        level: "free",
      },
      {
        name: "Octal Calculator",
        description: "Perform calculations in octal number system",
        icon: "🔢", // Replace with a professional icon
        slug: "octal-calculator",
        level: "free",
      },
      {
        name: "Percentage Calculator",
        description: "Calculate percentages, increases, and decreases",
        icon: "📊", // Replace with a professional icon
        slug: "percentage-calculator",
        level: "free",
      },
      {
        name: "Earnings Per Share Calculator",
        description: "Calculate earnings per share",
        icon: "📈", // Replace with a professional icon
        slug: "eps-calculator",
        level: "pro",
      },
      {
        name: "Probability Calculator",
        description: "Calculate probabilities for various events",
        icon: "🎲", // Replace with a professional icon
        slug: "probability-calculator",
        level: "pro",
      },
      {
        name: "Margin Calculator",
        description: "Calculate profit margins and markups",
        icon: "📈", // Replace with a professional icon
        slug: "margin-calculator",
        level: "free",
      },
      
      {
        name: "GST Calculator",
        description: "Calculate GST (Goods and Services Tax)",
        icon: "📋", // Replace with a professional icon
        slug: "gst-calculator",
        level: "free",
      },
      {
        name: "Lower and Upper Bound Calculator",
        description: "Calculate lower and upper bounds for data sets",
        icon: "📏", // Replace with a professional icon
        slug: "bound-calculator",
        level: "pro",
      },
      {
        name: "Average Calculator",
        description: "Calculate mean, median, and mode",
        icon: "📊", // Replace with a professional icon
        slug: "average-calculator",
        level: "free",
      },
      {
        name: "Sales Tax Calculator",
        description: "Calculate sales tax and gross price",
        icon: "📊", // Replace with a professional icon
        slug: "sales-tax-calculator",
        level: "free",
      },
      {
        name: "Age Calculator",
        description: "Calculate age in years, months, and days",
        icon: "🎂", // Replace with a professional icon
        slug: "age-calculator",
        level: "free",
      },
      {
        name: "Pre and Post Money Valuation",
        description: "Calculate pre and post money valuation for startups",
        icon: "💼", // Replace with a professional icon
        slug: "pre-and-post-money-valuation-calculator",
        level: "pro",
      },
    ],
  },
  // all
  converters: {
    name: "Converters",
    description: "Convert between different units, formats, and number systems",
    color: "from-teal-500 to-blue-500",
    tools: [
      {
        name: "RGB to Hex Converter",
        description: "Convert RGB colors to hexadecimal format",
        icon: "🌈",
        slug: "rgb-to-hex",
      },
      {
        name: "Hex to RGB Converter",
        description: "Convert hexadecimal colors to RGB format",
        icon: "🎨",
        slug: "hex-to-rgb",
      },
      // {
      //   name: "Currency Converter",
      //   description: "Convert between different currencies",
      //   icon: "💱",
      //   slug: "currency-converter",
      //   level: "pro",
      // },
      // {
      //   name: "Unit Converter",
      //   description: "Convert between various units of measurement",
      //   icon: "📏",
      //   slug: "unit-converter",
      //   level: "pro",
      // },
      {
        name: "Decimal to Octal",
        description: "Convert decimal numbers to octal format",
        icon: "🔢",
        slug: "decimal-to-octal",
        level: "free",
      },
      {
        name: "Octal to Decimal",
        description: "Convert octal numbers to decimal format",
        icon: "🔟",
        slug: "octal-to-decimal",
        level: "free",
      },
      // {
      //   name: "Active to Passive Voice Converter",
      //   description: "Convert active voice sentences to passive voice",
      //   icon: "🔄",
      //   slug: "active-to-passive-voice",
      //   level:"pro"
      // },
      // {
      //   name: "ICO Converter",
      //   description: "Convert images to ICO format",
      //   icon: "🖼️",
      //   slug: "ico-converter",
      //   level:"pro"
      // },
      {
        name: "Roman Numerals Date Converter",
        description: "Convert dates to Roman numeral format",
        icon: "📅",
        slug: "roman-numerals-date",
        level: "free"
      },
      {
        name: "Text to Binary Converter",
        description: "Convert text to binary format",
        icon: "💻",
        slug: "text-to-binary",
        level: "free"
      },
      {
        name: "Decimal to Binary Converter",
        description: "Convert decimal numbers to binary format",
        icon: "0️⃣1️⃣",
        slug: "decimal-to-binary",
        level: "free"
      },
      {
        name: "Binary to Decimal Converter",
        description: "Convert binary numbers to decimal format",
        icon: "1️⃣0️⃣",
        slug: "binary-to-decimal",
        level: "free"
      },
      {
        name: "Decimal to Hex Converter",
        description: "Convert decimal numbers to hexadecimal format",
        icon: "🔣",
        slug: "decimal-to-hex",
        level: "free"
      },
      {
        name: "Hex to Decimal Converter",
        description: "Convert hexadecimal numbers to decimal format",
        icon: "🔢",
        slug: "hex-to-decimal",
        level: "free"
      },
      {
        name: "Binary to Hex Converter",
        description: "Convert binary numbers to hexadecimal format",
        icon: "🔠",
        slug: "binary-to-hex",
        level: "free"
      },
      {
        name: "Hex to Binary Converter",
        description: "Convert hexadecimal numbers to binary format",
        icon: "🔡",
        slug: "hex-to-binary",
        level: "free"
      },
      {
        name: "Binary to Octal Converter",
        description: "Convert binary numbers to octal format",
        icon: "🔢",
        slug: "binary-to-octal",
        level: "free"
      },
      {
        name: "Hex to Octal Converter",
        description: "Convert hexadecimal numbers to octal format",
        icon: "🔢",
        slug: "hex-to-octal",
        level: "free"
      },
      {
        name: "Octal to Binary Converter",
        description: "Convert octal numbers to binary format",
        icon: "🔢",
        slug: "octal-to-binary",
        level: "free"
      },
      {
        name: "Octal to Hex Converter",
        description: "Convert octal numbers to hexadecimal format",
        icon: "🔢",
        slug: "octal-to-hex",
        level: "free"
      },
      {
        name: "Case Converter",
        description: "Convert text between different cases",
        icon: "🔠",
        slug: "case-converter",
      },
      {
        name: "ASCII to Hex Converter",
        description: "Convert ASCII characters to hexadecimal format",
        icon: "🔡",
        slug: "ascii-to-hex",
      },
      {
        name: "ASCII to Decimal Converter",
        description: "Convert ASCII characters to decimal format",
        icon: "🔢",
        slug: "ascii-to-decimal",
      },
      {
        name: "Decimal to ASCII Converter",
        description: "Convert decimal numbers to ASCII characters",
        icon: "🔡",
        slug: "decimal-to-ascii",
      },
      {
        name: "Hex to ASCII Converter",
        description: "Convert hexadecimal numbers to ASCII characters",
        icon: "🔡",
        slug: "hex-to-ascii",
      },
      {
        name: "Hex to Text Converter",
        description: "Convert hexadecimal numbers to text",
        icon: "🔤",
        slug: "hex-to-text",
      },
      {
        name: "Text to Hex Converter",
        description: "Convert text to hexadecimal format",
        icon: "🔠",
        slug: "text-to-hex",
      },
      {
        name: "Date Converter to Arabic, Roman, Bangla, and English",
        description: "Convert dates to various numeral systems",
        icon: "📆",
        slug: "multi-date-converter",
      },
    ],
  },
  // all
  generators: {
    name: "Generators",
    description: "Generate various types of content and data for your projects",
    color: "from-indigo-500 to-purple-500",
    tools: [
      // {
      //   name: "Meta Tag Generator",
      //   description: "Generate meta tags for your website",
      //   icon: "🏷️",
      //   slug: "meta-tag-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Robots.txt Generator",
      //   description: "Create robots.txt files for your website",
      //   icon: "🤖",
      //   slug: "robots-txt-generator",
      //   level: "pro",
      // },
      // {
      //   name: "XML Sitemap Generator",
      //   description: "Generate XML sitemaps for better SEO",
      //   icon: "🗺️",
      //   slug: "xml-sitemap-generator",
      //   level: "pro",
      // },
      // {
      //   name: "AI Story Generator",
      //   description: "Generate creative stories using AI",
      //   icon: "📖",
      //   slug: "ai-story-generator",
      //   level: "pro",
      // },
      // {
      //   name: "AI Poem Generator",
      //   description: "Create poems with the help of AI",
      //   icon: "📝",
      //   slug: "ai-poem-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Cover Letter Generator",
      //   description: "Generate professional cover letters",
      //   icon: "✉️",
      //   slug: "cover-letter-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Business Name Generator",
      //   description: "Generate unique business names",
      //   icon: "🏢",
      //   slug: "business-name-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Book Title Generator",
      //   description: "Create catchy book titles",
      //   icon: "📚",
      //   slug: "book-title-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Abstract Generator",
      //   description: "Generate abstracts for academic papers",
      //   icon: "📄",
      //   slug: "abstract-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Conclusion Generator",
      //   description: "Generate conclusions for essays and papers",
      //   icon: "🔚",
      //   slug: "conclusion-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Outline Generator",
      //   description: "Create outlines for your projects",
      //   icon: "🗂️",
      //   slug: "outline-generator",
      //   level: "pro",
      // },
      // {
      //   name: "AI Answer Generator",
      //   description: "Generate answers to questions using AI",
      //   icon: "💡",
      //   slug: "ai-answer-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Paragraph Generator",
      //   description: "Generate paragraphs for your content",
      //   icon: "📑",
      //   slug: "paragraph-generator",
      //   level: "pro",
      // },
      // {
      //   name: "AI Sentence Generator",
      //   description: "Create sentences using AI",
      //   icon: "✒️",
      //   slug: "ai-sentence-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Thesis Generator",
      //   description: "Generate thesis statements for essays",
      //   icon: "🎓",
      //   slug: "thesis-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Slogan Generator",
      //   description: "Create catchy slogans for your brand",
      //   icon: "📢",
      //   slug: "slogan-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Backstory Generator",
      //   description: "Generate backstories for characters",
      //   icon: "📜",
      //   slug: "backstory-generator",
      //   level: "pro",
      // },
      // {
      //   name: "FAQ Generator",
      //   description: "Create FAQs for your website",
      //   icon: "❓",
      //   slug: "faq-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Acronym Generator",
      //   description: "Generate acronyms for phrases",
      //   icon: "🔤",
      //   slug: "acronym-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Meta Description Generator",
      //   description: "Create meta descriptions for SEO",
      //   icon: "📝",
      //   slug: "meta-description-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Review Generator",
      //   description: "Generate reviews for products and services",
      //   icon: "⭐",
      //   slug: "review-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Caption Generator",
      //   description: "Create captions for images and videos",
      //   icon: "🖼️",
      //   slug: "caption-generator",
      //   level: "pro",
      // },
      // {
      //   name: "AI Message Generator",
      //   description: "Generate messages using AI",
      //   icon: "💬",
      //   slug: "ai-message-generator",
      //   level: "pro",
      // },
      // {
      //   name: "AI Reply Generator",
      //   description: "Generate replies to messages using AI",
      //   icon: "🔄",
      //   slug: "ai-reply-generator",
      //   level: "pro",
      // },
      // {
      //   name: "AI Prompt Generator",
      //   description: "Create prompts for AI models",
      //   icon: "🧠",
      //   slug: "ai-prompt-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Tiny Text Generator",
      //   description: "Generate tiny text for social media",
      //   icon: "🔠",
      //   slug: "tiny-text-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Small Text Generator",
      //   description: "Create small text for various uses",
      //   icon: "🔡",
      //   slug: "small-text-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Essay Generator",
      //   description: "Generate essays on various topics",
      //   icon: "📄",
      //   slug: "essay-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Favicon Generator",
      //   description: "Generate favicons for your website",
      //   icon: "🎯",
      //   slug: "favicon-generator",
      //   level: "pro",
      // },
      // {
      //   name: "QR Code Generator",
      //   description: "Generate QR codes for text, URLs, and more",
      //   icon: "📱",
      //   slug: "qr-code-generator",
      //   level: "pro",
      // },
      {
        name: "Reverse Text Generator",
        description: "Reverse the text input",
        icon: "🔄",
        slug: "reverse-text-generator",
        level: "free",
      },
      {
        name: "Upside Down Text Generator",
        description: "Flip text upside down",
        icon: "🔄",
        slug: "upside-down-text-generator",
        level: "free",
      },
      // {
      //   name: "Random Address Generator",
      //   description: "Generate random addresses for testing",
      //   icon: "🏠",
      //   slug: "random-address-generator",
      //   level: "pro",
      // },
      {
        name: "Password Generator",
        description: "Generate secure passwords",
        icon: "🔑",
        slug: "password-generator",
        level: "free",
      },
      // {
      //   name: "Fake Name Generator",
      //   description: "Generate fake names for testing",
      //   icon: "👤",
      //   slug: "fake-name-generator",
      //   level: "pro",
      // },
      // {
      //   name: "Random Word Generator",
      //   description: "Generate random words for inspiration",
      //   icon: "🔤",
      //   slug: "random-word-generator",
      //   level: "pro",
      // },
    ],
  },
  // all
  "seo-tools": {
    name: "SEO Tools",
    description:
      "Search engine optimization tools to improve your website's ranking",
    color: "from-yellow-500 to-orange-500",
    tools: [
      {
        name: "Backlink Maker",
        description: "Create backlinks to improve SEO",
        icon: "🔗",
        slug: "backlink-maker",
        level: "pro",
      },
      {
        name: "Google Index Checker",
        description: "Check if your pages are indexed by Google",
        icon: "🔍",
        slug: "google-index-checker",
        level: "free",
      },
      {
        name: "Search Engine Spider Simulator",
        description: "Simulate how search engine spiders view your site",
        icon: "🕷️",
        slug: "search-engine-spider-simulator",
        level: "pro",
      },
      {
        name: "Meta Tags Analyzer",
        description: "Analyze the meta tags of your website",
        icon: "🏷️",
        slug: "meta-tags-analyzer",
        level: "free",
      },
      {
        name: "Verify Backlink",
        description: "Verify the existence of backlinks to your site",
        icon: "🔗",
        slug: "verify-backlink",
        level: "pro",
      },
      {
        name: "SEO Friendly URLs Checker",
        description: "Check if your URLs are SEO friendly",
        icon: "🔗",
        slug: "seo-friendly-urls-checker",
        level: "free",
      },
      {
        name: "Text Summarizer",
        description: "Summarize text content for quick insights",
        icon: "📝",
        slug: "text-summarizer",
        level: "pro",
      },
      {
        name: "Alexa Rank Checker",
        description: "Check website's Alexa traffic ranking",
        icon: "📈",
        slug: "alexa-rank-checker",
        level: "free",
      },
      {
        name: "Compare Alexa Rank Checker",
        description: "Compare Alexa rankings of different websites",
        icon: "📊",
        slug: "compare-alexa-rank-checker",
        level: "pro",
      },
      {
        name: "Social Media Counter",
        description: "Count social media shares for any URL",
        icon: "📱",
        slug: "social-media-counter",
        level: "free",
      },
      {
        name: "Google PR Checker",
        description: "Check Google PageRank for websites",
        icon: "📊",
        slug: "google-pr-checker",
        level: "pro",
      },
      {
        name: "Google Indexer",
        description: "Index your pages with Google",
        icon: "🔍",
        slug: "google-indexer",
        level: "pro",
      },
      {
        name: "Website SEO Score Checker",
        description: "Check the SEO score of your website",
        icon: "📊",
        slug: "website-seo-score-checker",
        level: "free",
      },
    ],
  },
  // all
  "productivity-tools": {
    name: "Productivity Tools",
    description:
      "Tools to boost your productivity and streamline your workflow",
    color: "from-cyan-500 to-blue-500",
    tools: [
      {
        name: "Timer",
        description: "Set timers for various tasks and activities",
        icon: "⏰",
        slug: "timer",
      },
      {
        name: "Calendar",
        description: "View and manage calendar dates",
        icon: "📅",
        slug: "calendar",
      },
      {
        name: "Dictionary",
        description: "Look up word definitions and meanings",
        icon: "📚",
        slug: "dictionary",
      },
      {
        name: "Basic Calculator",
        description: "Perform basic mathematical calculations",
        icon: "🧮",
        slug: "calculator",
      },
    ],
  },
  // all
  "image-tools": {
    name: "Image Tools",
    description: "Image editing, conversion, and analysis tools",
    color: "from-cyan-500 to-blue-500",
    tools: [
      // {
      //   name: "Image Translator",
      //   description: "Translate text within images to different languages",
      //   icon: "🌐",
      //   slug: "image-translator",
      //   level: "pro",
      // },
      // {
      //   name: "Barcode Scanner",
      //   description: "Scan and decode barcodes from images",
      //   icon: "📷",
      //   slug: "barcode-scanner",
      //   level: "free",
      // },
      // {
      //   name: "Image to Excel",
      //   description: "Convert images of tables into Excel format",
      //   icon: "📊",
      //   slug: "image-to-excel",
      //   level: "pro",
      // },
      // {
      //   name: "Reverse Image Search",
      //   description: "Find similar images across the web",
      //   icon: "🔍",
      //   slug: "reverse-image-search",
      //   level: "free",
      // },
      // {
      //   name: "Image to Text",
      //   description: "Extract text from images",
      //   icon: "📝",
      //   slug: "image-to-text",
      //   level: "free",
      // },
      // {
      //   name: "Crop Image Online",
      //   description: "Crop images to desired dimensions",
      //   icon: "✂️",
      //   slug: "crop-image-online",
      //   level: "free",
      // },
      {
        name: "Binary Translator",
        description: "Translate binary code to text and vice versa",
        icon: "0️⃣1️⃣",
        slug: "binary-translator",
        level: "free",
      },
      {
        name: "Text to Image",
        description: "Convert text into an image format",
        icon: "🖼️",
        slug: "text-to-image",
        level: "free",
      },
      // {
      //   name: "JPG to Word",
      //   description: "Convert JPG images to Word documents",
      //   icon: "📄",
      //   slug: "jpg-to-word",
      //   level: "pro",
      // },
      // {
      //   name: "PDF to Text",
      //   description: "Extract text from PDF files",
      //   icon: "📄",
      //   slug: "pdf-to-text",
      //   level: "pro",
      // },
      {
        name: "Text to Handwriting",
        description: "Convert typed text into a handwriting style",
        icon: "✍️",
        slug: "text-to-handwriting",
        level: "free",
      },
      // {
      //   name: "PDF to Word",
      //   description: "Convert PDF documents to Word format",
      //   icon: "📄",
      //   slug: "pdf-to-word",
      //   level: "pro",
      // },
    ],
  },
};

export const categories = [
  {
    name: "Text Tools",
    icon: Type,
    count: 10,
    description: "Text manipulation, formatting, and analysis tools",
    tools: ["Word Counter", "Text Case Converter"],
  },
  {
    name: "Image Tools",
    icon: ImageIcon,
    count: 3,
    description: "Image editing, compression, and conversion tools",
    tools: ["Image Compressor", "Image Resizer", "Background Remover"],
  },
  {
    name: "Developer Tools",
    icon: Code,
    count: 16,
    description: "Development utilities and code generators",
    tools: ["JSON Formatter", "Base64 Encoder", "Hash Generator"],
  },
  // {
  //   name: "SEO Tools",
  //   icon: BarChart3,
  //   count: 13,
  //   description: "Search engine optimization and analysis tools",
  //   tools: [
  //     "Meta Tag Generator",
  //     "Keyword Density Checker",
  //     "Robots.txt Generator",
  //   ],
  // },
  {
    name: "Calculators",
    icon: Calculator,
    count: 17,
    description: "Mathematical and financial calculators",
    tools: ["Percentage Calculator", "BMI Calculator", "Loan Calculator"],
  },
  {
    name: "Converters",
    icon: Shuffle,
    count: 24,
    description: "Unit and format conversion tools",
    tools: ["Unit Converter", "Currency Converter", "Color Converter"],
  },
  {
    name: "Generators",
    icon: Palette,
    count: 3,
    description: "Content and data generation tools",
    tools: ["Password Generator", "QR Code Generator", "UUID Generator"],
  },
  // {
  //   name: "Productivity",
  //   icon: FileText,
  //   count: 4,
  //   description: "Tools to boost your daily productivity",
  //   tools: ["PDF Tools", "Time Zone Converter", "Pomodoro Timer"],
  // },
  // {
  //   name: "Domain Tools",
  //   icon: Globe,
  //   count: 15,
  //   description: "Domain analysis and management tools",
  //   tools: ["Domain Authority Checker", "Whois Lookup", "DNS Records"],
  // },
  {
    name: "Website Management",
    icon: Settings,
    count: 3,
    description: "Website analysis and management utilities",
    tools: ["Server Status Checker", "Website Speed Test", "SSL Checker"],
  },
  // {
  //   name: "More Tools",
  //   icon: Plus,
  //   count: 3,
  //   description: "Additional specialized tools and utilities",
  //   tools: ["QR Code Scanner", "Random Name Generator", "Color Palette"],
  // },
];

export const featuredTools = [
  {
    name: "Password Generator",
    description: "Generate secure passwords with custom options",
    category: "Security",
    link: "generators/password-generator",
    popular: true,
  },
  // {
  //   name: "QR Code Generator",
  //   description: "Create QR codes for text, URLs, and more",
  //   category: "Generators",
  //   popular: true,
  // },
  // {
  //   name: "Image Compressor",
  //   description: "Reduce image file size without quality loss",
  //   category: "Image Tools",
  //   popular: true,
  // },
  {
    name: "JSON Formatter",
    description: "Format and validate JSON data",
    category: "Developer Tools",
    link: "developer-tools/json-beautifier",
    popular: false,
  },
  {
    name: "Word Counter",
    description: "Count words, characters, and paragraphs",
    category: "Text Tools",
    link: "text-tools/word-counter",
    popular: true,
  },
  // {
  //   name: "Color Picker",
  //   description: "Pick colors and get hex, RGB, HSL values",
  //   category: "Design Tools",
  //   popular: false,
  // },
];


export interface ITool {
  name: string
  description: string
  category: string
  slug: string
  categorySlug: string
  icon?: string
}


export const SearchedAllTools: ITool[] = [
  // ===============================Domain Tools=================================
  // {
  //   name: "Domain Authority Checker",
  //   description: "Check domain authority and page authority scores",
  //   category: "Domain Tools",
  //   slug: "domain-authority-checker",
  //   categorySlug: "domain-tools",
  //   icon: "🔍",
  // },
  // {
  //   name: "Domain Age Checker",
  //   description: "Find out when a domain was first registered",
  //   category: "Domain Tools",
  //   slug: "domain-age-checker",
  //   categorySlug: "domain-tools",
  //   icon: "📅",
  // },
  // {
  //   name: "Domain Whois Checker",
  //   description: "Get detailed whois information for any domain",
  //   category: "Domain Tools",
  //   slug: "domain-whois-checker",
  //   categorySlug: "domain-tools",
  //   icon: "ℹ️",
  // },
  // {
  //   name: "Domain IP History",
  //   description: "View historical IP addresses for any domain",
  //   category: "Domain Tools",
  //   slug: "domain-ip-history",
  //   categorySlug: "domain-tools",
  //   icon: "📊",
  // },
  // {
  //   name: "Reverse IP Domains",
  //   description: "Find all domains hosted on the same IP address",
  //   category: "Domain Tools",
  //   slug: "reverse-ip-domains",
  //   categorySlug: "domain-tools",
  //   icon: "🔄",
  // },
  // {
  //   name: "Google Malware Checker",
  //   description: "Check if a website is flagged by Google for malware",
  //   category: "Domain Tools",
  //   slug: "google-malware-checker",
  //   categorySlug: "domain-tools",
  //   icon: "🛡️",
  // },
  // {
  //   name: "Backlink Maker",
  //   description: "Generate high-quality backlinks for your website",
  //   category: "Domain Tools",
  //   slug: "backlink-maker",
  //   categorySlug: "domain-tools",
  //   icon: "🔗",
  // },
  // {
  //   name: "Broken Links Checker",
  //   description: "Find and fix broken links on your website",
  //   category: "Domain Tools",
  //   slug: "broken-links-checker",
  //   categorySlug: "domain-tools",
  //   icon: "🔧",
  // },
  // {
  //   name: "Google Indexer",
  //   description: "Check if your pages are indexed by Google",
  //   category: "Domain Tools",
  //   slug: "google-indexer",
  //   categorySlug: "domain-tools",
  //   icon: "🔍",
  // },
  // {
  //   name: "Reverse Whois Checker",
  //   description: "Find domains registered by the same person or organization",
  //   category: "Domain Tools",
  //   slug: "reverse-whois-checker",
  //   categorySlug: "domain-tools",
  //   icon: "👤",
  // },
  // {
  //   name: "Alexa Rank Checker",
  //   description: "Check website's Alexa traffic ranking",
  //   category: "Domain Tools",
  //   slug: "alexa-rank-checker",
  //   categorySlug: "domain-tools",
  //   icon: "📈",
  // },

  // ==============================Developer Tools=============================
  {
    name: "DNS Records Checker",
    description: "Check DNS records for any domain",
    category: "Developer Tools",
    slug: "dns-records",
    categorySlug: "developer-tools",
    icon: "🌐",
  },
  {
    name: "HTML Encoder/Decoder",
    description: "Encode and decode HTML entities",
    category: "Developer Tools",
    slug: "html-encoder-decoder",
    categorySlug: "developer-tools",
    icon: "📝",
  },
  {
    name: "JSON Beautifier",
    description: "Format and validate JSON data",
    category: "Developer Tools",
    slug: "json-beautifier",
    categorySlug: "developer-tools",
    icon: "📋",
  },
  {
    name: "Minify HTML",
    description: "Compress HTML code by removing unnecessary characters",
    category: "Developer Tools",
    slug: "minify-html",
    categorySlug: "developer-tools",
    icon: "🗜️",
  },
  {
    name: "JS Beautifier",
    description: "Format and beautify JavaScript code",
    category: "Developer Tools",
    slug: "js-beautifier",
    categorySlug: "developer-tools",
    icon: "✨",
  },
  {
    name: "PHP Beautifier",
    description: "Format and beautify PHP code",
    category: "Developer Tools",
    slug: "php-beautifier",
    categorySlug: "developer-tools",
    icon: "🐘",
  },
  {
    name: "XML Beautifier",
    description: "Format and validate XML data",
    category: "Developer Tools",
    slug: "xml-beautifier",
    categorySlug: "developer-tools",
    icon: "📄",
  },
  {
    name: "Server Status Checker",
    description: "Check if a server is online and responsive",
    category: "Developer Tools",
    slug: "server-status",
    categorySlug: "developer-tools",
    icon: "🖥️",
  },
  {
    name: "CSS Beautifier",
    description: "Format and beautify CSS code",
    category: "Developer Tools",
    slug: "css-beautifier",
    categorySlug: "developer-tools",
    icon: "🎨",
  },
  {
    name: "URL Encoder/Decoder",
    description: "Encode and decode URLs",
    category: "Developer Tools",
    slug: "url-encoder-decoder",
    categorySlug: "developer-tools",
    icon: "🔗",
  },
  {
    name: "Get Source Code of Webpage",
    description: "Retrieve the source code of any webpage",
    category: "Developer Tools",
    slug: "source-code-retriever",
    categorySlug: "developer-tools",
    icon: "📜",
  },
  {
    name: "Minify CSS",
    description: "Compress CSS code by removing unnecessary characters",
    category: "Developer Tools",
    slug: "minify-css",
    categorySlug: "developer-tools",
    icon: "🗜️",
  },
  {
    name: "Minify JS",
    description: "Compress JavaScript code by removing unnecessary characters",
    category: "Developer Tools",
    slug: "minify-js",
    categorySlug: "developer-tools",
    icon: "🗜️",
  },
  {
    name: "Minify JSON",
    description: "Compress JSON data by removing unnecessary characters",
    category: "Developer Tools",
    slug: "minify-json",
    categorySlug: "developer-tools",
    icon: "🗜️",
  },

  // ========================Text Tools========================
  {
    name: "Word Counter",
    description: "Count the number of words in a text",
    category: "Text Tools",
    slug: "word-counter",
    categorySlug: "text-tools",
    icon: "🔢",
  },
  {
    name: "Code to Text Ratio Checker",
    description: "Calculate the code to text ratio in a document",
    category: "Text Tools",
    slug: "code-to-text-ratio",
    categorySlug: "text-tools",
    icon: "📊",
  },
  {
    name: "Invisible Character",
    description: "Insert invisible characters into text",
    category: "Text Tools",
    slug: "invisible-character",
    categorySlug: "text-tools",
    icon: "👻",
  },
  {
    name: "Text to Word",
    description: "Convert text documents to Word format",
    category: "Text Tools",
    slug: "text-to-word",
    categorySlug: "text-tools",
    icon: "📄",
  },
  {
    name: "Text to PDF",
    description: "Convert text documents to PDF format",
    category: "Text Tools",
    slug: "text-to-pdf",
    categorySlug: "text-tools",
    icon: "📄",
  },
  {
    name: "Text Repeater",
    description: "Repeat text multiple times",
    category: "Text Tools",
    slug: "text-repeater",
    categorySlug: "text-tools",
    icon: "🔁",
  },
  {
    name: "Word Combiner",
    description: "Combine words to create new terms",
    category: "Text Tools",
    slug: "word-combiner",
    categorySlug: "text-tools",
    icon: "🔗",
  },
  {
    name: "ASCII to Text",
    description: "Convert ASCII codes to text",
    category: "Text Tools",
    slug: "ascii-to-text",
    categorySlug: "text-tools",
    icon: "🔤",
  },
  {
    name: "Text to ASCII",
    description: "Convert text to ASCII codes",
    category: "Text Tools",
    slug: "text-to-ascii",
    categorySlug: "text-tools",
    icon: "🔤",
  },
  {
    name: "Words to Pages",
    description: "Calculate the number of pages from word count",
    category: "Text Tools",
    slug: "word-pages",
    categorySlug: "text-tools",
    icon: "📄",
  },
  {
    name: "Binary Translator",
    description: "Convert text to binary and vice versa",
    category: "Text Tools",
    slug: "binary-translator",
    categorySlug: "text-tools",
    icon: "🔢",
  },

  // {
  //   name: "Roman Numeral Converter",
  //   description: "Convert numbers to Roman numerals and back",
  //   category: "Text Tools",
  //   slug: "roman-numeral-converter",
  //   categorySlug: "text-tools",
  //   icon: "🏛️",
  // },
  // {
  //   name: "Text to Hex Converter",
  //   description: "Convert text to hexadecimal format",
  //   category: "Text Tools",
  //   slug: "text-to-hex",
  //   categorySlug: "text-tools",
  //   icon: "🔤",
  // },
  // {
  //   name: "Random Word Generator",
  //   description: "Generate random words for various purposes",
  //   category: "Text Tools",
  //   slug: "random-word-generator",
  //   categorySlug: "text-tools",
  //   icon: "🎲",
  // },
  // {
  //   name: "Grammar Checker",
  //   description: "Check and correct grammar in your text",
  //   category: "Text Tools",
  //   slug: "grammar-checker",
  //   categorySlug: "text-tools",
  //   icon: "✅",
  // },

  // ==========================Calculators=============================

  
    {
      name: "Link Price Calculator",
      description: "Calculate the price of links based on various metrics",
      category: "Calculators",
      slug: "link-price-calculator",
      categorySlug: "calculators",
      icon: "🔗",
    },
    {
      name: "AdSense Calculator",
      description: "Calculate potential AdSense earnings",
      category: "Calculators",
      slug: "adsense-calculator",
      categorySlug: "calculators",
      icon: "💵",
    },
    {
      name: "PayPal Fee Calculator",
      description: "Calculate PayPal transaction fees",
      category: "Calculators",
      slug: "paypal-fee-calculator",
      categorySlug: "calculators",
      icon: "💳",
    },
    {
      name: "LTV Calculator",
      description: "Calculate customer lifetime value",
      category: "Calculators",
      slug: "ltv-calculator",
      categorySlug: "calculators",
      icon: "📈",
    },
    {
      name: "CPC Calculator",
      description: "Calculate cost per click for advertising",
      category: "Calculators",
      slug: "cpc-calculator",
      categorySlug: "calculators",
      icon: "📊",
    },
    {
      name: "CPM Calculator",
      description: "Calculate cost per mille for advertising",
      category: "Calculators",
      slug: "cpm-calculator",
      categorySlug: "calculators",
      icon: "📊",
    },
    // {
    //   name: "Discount Calculator",
    //   description: "Calculate discounts and final prices",
    //   category: "Calculators",
    //   slug: "discount-calculator",
    //   categorySlug: "calculators",
    //   icon: "💰",
    // },
    {
      name: "Binary Calculator",
      description: "Perform calculations in binary number system",
      category: "Calculators",
      slug: "binary-calculator",
      categorySlug: "calculators",
      icon: "🔢",
    },
    {
      name: "HEX Calculator",
      description: "Perform calculations in hexadecimal number system",
      category: "Calculators",
      slug: "hex-calculator",
      categorySlug: "calculators",
      icon: "🔢",
    },
    {
      name: "Octal Calculator",
      description: "Perform calculations in octal number system",
      category: "Calculators",
      slug: "octal-calculator",
      categorySlug: "calculators",
      icon: "🔢",
    },
    // {
    //   name: "Percentage Calculator",
    //   description: "Calculate percentages, increases, and decreases",
    //   category: "Calculators",
    //   slug: "percentage-calculator",
    //   categorySlug: "calculators",
    //   icon: "📊",
    // },
    // {
    //   name: "Earnings Per Share Calculator",
    //   description: "Calculate earnings per share",
    //   category: "Calculators",
    //   slug: "eps-calculator",
    //   categorySlug: "calculators",
    //   icon: "📈",
    // },
    {
      name: "Probability Calculator",
      description: "Calculate probabilities for various events",
      category: "Calculators",
      slug: "probability-calculator",
      categorySlug: "calculators",
      icon: "🎲",
    },
    // {
    //   name: "Margin Calculator",
    //   description: "Calculate profit margins and markups",
    //   category: "Calculators",
    //   slug: "margin-calculator",
    //   categorySlug: "calculators",
    //   icon: "📈",
    // },
   
    {
      name: "GST Calculator",
      description: "Calculate GST (Goods and Services Tax)",
      category: "Calculators",
      slug: "gst-calculator",
      categorySlug: "calculators",
      icon: "📋",
    },
    {
      name: "Lower and Upper Bound Calculator",
      description: "Calculate lower and upper bounds for data sets",
      category: "Calculators",
      slug: "bound-calculator",
      categorySlug: "calculators",
      icon: "📏",
    },
    {
      name: "Average Calculator",
      description: "Calculate mean, median, and mode",
      category: "Calculators",
      slug: "average-calculator",
      categorySlug: "calculators",
      icon: "📊",
    },
    // {
    //   name: "Age Calculator",
    //   description: "Calculate age in years, months, and days",
    //   category: "Calculators",
    //   slug: "age-calculator",
    //   categorySlug: "calculators",
    //   icon: "🎂",
    // },
    {
      name: "Pre and Post Money Valuation",
      description: "Calculate pre and post money valuation for startups",
      category: "Calculators",
      slug: "pre-and-post-money-valuation-calculator",
      categorySlug: "calculators",
      icon: "💼",
    },
  
    ///
  {
    name: "Percentage Calculator",
    description: "Calculate percentages, increases, and decreases",
    category: "Calculators",
    slug: "percentage-calculator",
    categorySlug: "calculators",
    icon: "📊",
  },
  {
    name: "Age Calculator",
    description: "Calculate age in years, months, and days",
    category: "Calculators",
    slug: "age-calculator",
    categorySlug: "calculators",
    icon: "🎂",
  },
  {
    name: "Discount Calculator",
    description: "Calculate discounts and final prices",
    category: "Calculators",
    slug: "discount-calculator",
    categorySlug: "calculators",
    icon: "💰",
  },
  {
    name: "Sales Tax Calculator",
    description: "Calculate sales tax and total amount",
    category: "Calculators",
    slug: "sales-tax-calculator",
    categorySlug: "calculators",
    icon: "🧾",
  },
  {
    name: "GST Calculator",
    description: "Calculate GST (Goods and Services Tax)",
    category: "Calculators",
    slug: "gst-calculator",
    categorySlug: "calculators",
    icon: "📋",
  },
  {
    name: "Margin Calculator",
    description: "Calculate profit margins and markups",
    category: "Calculators",
    slug: "margin-calculator",
    categorySlug: "calculators",
    icon: "📈",
  },
  {
    name: "Interest Calculator",
    description: "Calculate simple and compound interest",
    category: "Calculators",
    slug: "interest-calculator",
    categorySlug: "calculators",
    icon: "🏦",
  },
  // {
  //   name: "Average Calculator",
  //   description: "Calculate mean, median, and mode",
  //   category: "Calculators",
  //   slug: "average-calculator",
  //   categorySlug: "calculators",
  //   icon: "📊",
  // },

  // ==========================Converters=============================
  {
    name: "RGB to Hex Converter",
    description: "Convert RGB colors to hexadecimal format",
    category: "Converters",
    slug: "rgb-to-hex",
    categorySlug: "converters",
    icon: "🎨",
  },
  {
    name: "Hex to RGB Converter",
    description: "Convert hexadecimal colors to RGB format",
    category: "Converters",
    slug: "hex-to-rgb",
    categorySlug: "converters",
    icon: "🌈",
  },
  {
    name: "Currency Converter",
    description: "Convert between different currencies",
    category: "Converters",
    slug: "currency-converter",
    categorySlug: "converters",
    icon: "💱",
  },
  {
    name: "Unit Converter",
    description: "Convert between various units of measurement",
    category: "Converters",
    slug: "unit-converter",
    categorySlug: "converters",
    icon: "📏",
  },

  // ==================================Generators=============================
  {
    name: "Password Generator",
    description: "Generate secure passwords with custom options",
    category: "Generators",
    slug: "password-generator",
    categorySlug: "generators",
    icon: "🔐", 
  },
  {
    name: "Reverse Text Generator",
    description: "Reverse any text string",
    category: "Generators Tools",
    slug: "reverse-text-generator",
    categorySlug: "generators",
    icon: "🔄",
  },
  {
    name: "Upside Down Text Generator",
    description: "Flip text upside down",
    category: "Generators",
    slug: "upside-down-text-generator",
    categorySlug: "generators",
    icon: "🙃",
  },
  // {
  //   name: "QR Code Generator",
  //   description: "Generate QR codes for text, URLs, and more",
  //   category: "Generators",
  //   slug: "qr-code-generator",
  //   categorySlug: "generators",
  //   icon: "📱",
  // },
  // {
  //   name: "Random Address Generator",
  //   description: "Generate random addresses for testing",
  //   category: "Generators",
  //   slug: "random-address-generator",
  //   categorySlug: "generators",
  //   icon: "🏠",
  // },
  // {
  //   name: "Email Template Generator",
  //   description: "Create professional email templates",
  //   category: "Generators",
  //   slug: "email-template-generator",
  //   categorySlug: "generators",
  //   icon: "📧",
  // },
  // {
  //   name: "Favicon Generator",
  //   description: "Generate favicons for your website",
  //   category: "Generators",
  //   slug: "favicon-generator",
  //   categorySlug: "generators",
  //   icon: "🎯",
  // },

  // ===========================SEO Tools======================
  // {
  //   name: "Website SEO Score",
  //   description: "Analyze your website's SEO performance",
  //   category: "SEO Tools",
  //   slug: "website-seo-score",
  //   categorySlug: "seo-tools",
  //   icon: "📊",
  // },
  // {
  //   name: "Google Index Checker",
  //   description: "Check if your pages are indexed by Google",
  //   category: "SEO Tools",
  //   slug: "google-index-tool",
  //   categorySlug: "seo-tools",
  //   icon: "🔍",
  // },
  // {
  //   name: "CMS Detector",
  //   description: "Detect what CMS a website is using",
  //   category: "SEO Tools",
  //   slug: "detect-cms",
  //   categorySlug: "seo-tools",
  //   icon: "🔍",
  // },

  // ==========================Productivity Tools=============================
  // {
  //   name: "Timer",
  //   description: "Set timers for various tasks and activities",
  //   category: "Productivity Tools",
  //   slug: "timer",
  //   categorySlug: "productivity-tools",
  //   icon: "⏰",
  // },
  // {
  //   name: "Calendar",
  //   description: "View and manage calendar dates",
  //   category: "Productivity Tools",
  //   slug: "calendar",
  //   categorySlug: "productivity-tools",
  //   icon: "📅",
  // },
  // {
  //   name: "Dictionary",
  //   description: "Look up word definitions and meanings",
  //   category: "Productivity Tools",
  //   slug: "dictionary",
  //   categorySlug: "productivity-tools",
  //   icon: "📚",
  // },
  // {
  //   name: "Basic Calculator",
  //   description: "Perform basic mathematical calculations",
  //   category: "Productivity Tools",
  //   slug: "calculator",
  //   categorySlug: "productivity-tools",
  //   icon: "🧮",
  // },
  // ====================Image tools==================================
  // {
  //   name: "Binary Translator",
  //   description: "Convert text to binary and vice versa",
  //   category: "Image Tools",
  //   slug: "binary-translator",
  //   categorySlug: "text-tools",
  //   icon: "🔢",
  // },
  {
    name: "Text to Image",
    description: "Convert text into an image format",
    category: "Image Tools",
    slug: "text-to-image",
    categorySlug: "image-tools",
    icon: "🖼️",
  },
  {
    name: "Text to Handwriting",
    description: "Convert typed text into a handwriting style",
    category: "Image Tools",
    slug: "text-to-handwriting",
    categorySlug: "image-tools",
    icon: "✍️",
  },
  // {
  //   name: "Image Translator",
  //   description: "Translate text within images to different languages",
  //   category: "Image Tools",
  //   slug: "image-translator",
  //   categorySlug: "image-tools",
  //   icon: "🌐",
  // },
  // {
  //   name: "Barcode Scanner",
  //   description: "Scan and decode barcodes from images",
  //   category: "Image Tools",
  //   slug: "barcode-scanner",
  //   categorySlug: "image-tools",
  //   icon: "📷",

  // },
  // {
  //   name: "Image to Excel",
  //   description: "Convert images of tables into Excel format",
  //   category: "Image Tools",
  //   slug: "image-to-excel",
  //   categorySlug: "image-tools",
  //   icon: "📊",

  // },
  // {
  //   name: "Reverse Image Search",
  //   description: "Find similar images across the web",
  //   category: "Image Tools",
  //   slug: "reverse-image-search",
  //   categorySlug: "image-tools",
  //   icon: "🔍",

  // },
  // {
  //   name: "Image to Text",
  //   description: "Extract text from images",
  //   category: "Image Tools",
  //   slug: "image-to-text",
  //   categorySlug: "image-tools",
  //   icon: "📝",

  // },
  // {
  //   name: "Crop Image Online",
  //   description: "Crop images to desired dimensions",
  //   category: "Image Tools",
  //   slug: "crop-image-online",
  //   categorySlug: "image-tools",
  //   icon: "✂️",

  // },
  // {
  //   name: "JPG to Word",
  //   description: "Convert JPG images to Word documents",
  //   category: "Image Tools",
  //   slug: "jpg-to-word",
  //   categorySlug: "image-tools",
  //   icon: "📄",

  // },
  // {
  //   name: "PDF to Text",
  //   description: "Extract text from PDF files",
  //   category: "Image Tools",
  //   slug: "pdf-to-text",
  //   categorySlug: "image-tools",
  //   icon: "📄",

  // },
  // {
  //   name: "PDF to Word",
  //   description: "Convert PDF documents to Word format",
  //   category: "Image Tools",
  //   slug: "pdf-to-word",
  //   categorySlug: "image-tools",

  // },
]